### ISSUE TITLE
NoSuchMethodError of TomcatAccessEvent

### ISSUE THREAD

**Issue by dinhnv** [akihyro/spring-boot-ext-logback-access#21]
Hi man,
I use verison 1.6 in my Spring Boot project (Spring Boot version 1.3.3.RELEASE) and got an error:
```

java.lang.NoSuchMethodError: net.rakugakibox.springbootext.logback.access.tomcat.TomcatAccessEvent.setThreadName(Ljava/lang/String;)V
	at net.rakugakibox.springbootext.logback.access.tomcat.LogbackAccessValve.log(LogbackAccessValve.java:125)
	at org.apache.catalina.core.AccessLogAdapter.log(AccessLogAdapter.java:51)
	at org.apache.catalina.core.ContainerBase.logAccess(ContainerBase.java:1042)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:571)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Please help me verify the issue. 
Thanks.

**Comment by akihyro** [comment]
In your project, what version of Logback-access?

In the case of Spring Boot 1.3.3.RELEASE, it will be used Logback-access 1.1.5 by default.
But, "spring-boot-ext-logback-access" requires Logback-access 1.1.6 or higher.

Please use Spring Boot 1.3.4.RELEASE (Logback-access 1.1.7 by default) or higher.
Or, please use Logback-access 1.1.6 or higher.

For example on Maven-based projects (`pom.xml`):

```xml
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.3.4.RELEASE</version>
</parent>
```

or

```xml
<properties>
    <logback.version>1.1.6</logback.version>
</properties>
```

**Comment by dinhnv** [comment]
Thank for your reply.
The issue was caused by Spring Boot version 1.3.3.RELEASE with default logback-access 1.1.5 as you mention.
The document about "Spring Boot 1.3.0+" together with "Logback-access 1.1.6+" sometimes makes confusion.
I decide to upgrade Spring Boot version and It works well.
Thank for your support.

**Comment by akihyro** [comment]
You're welcome.

I added a description about the version of Logback-access :)

https://github.com/akihyro/spring-boot-ext-logback-access/commit/79180d8ad0ba598f87fe31a99ee664a950f73fb9

**Comment by dinhnv** [comment]
Thank for your support. 

I'm using Gradle. 

So where can I specific logback.version globally?

**Comment by akihyro** [comment]
Sorry for the late reply.
I have never used Gradle, so I can not help it properly.

Can the following articles help you?

> [79.1 Customize dependency versions - Spring Boot Reference Guide](http://docs.spring.io/spring-boot/docs/1.3.3.RELEASE/reference/htmlsingle/#howto-customize-dependency-versions)
> 
> To override dependency versions in Gradle, you can specify a version as shown below:
> 
> ```
> ext['slf4j.version'] = '1.7.5'
> ```
> 
> For additional information, please refer to the [Gradle Dependency Management Plugin documentation](https://github.com/spring-gradle-plugins/dependency-management-plugin).

**Comment by dinhnv** [comment]
@akihyro Actually I've already configured it out. Thank you.
